apiVersion: apps/v1  # Specifies Kubernetes API version
kind: Deployment  # Defines the type of resource
metadata:
  name: devops-app  # Name of the deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: devops-app  # Defines pod labels to match
  template:
    metadata:
      labels:
        app: devops-app  # Label to identify pods
    spec:
      containers:bamendagirl        - name:  # Name of the container
          image: 891377331437.dkr.ecr.us-east-1.amazonaws.com/bamendagirl:cf752a2da6cdf0599b6ef87a41831e3ace7671c1          
          ports:
            - containerPort: 80  # Exposing port
